### ISSUE TITLE
총학생회 로그인 라이브러리 버튼 컴포넌트 개발

### ISSUE THREAD

**Issue by chchaeun** [GIFTERZ/dankook-text-me-client#3]
### 배경
- 총학생회 OAuth 사용을 위해 라이브러리 개발 필요

### 현재 상태
- 레포지토리를 파고 의존성 설치
- 임시 컴포넌트로 모듈 빌드 동작 확인

### 요구사항
- 총학생회로 로그인하기 버튼을 누르면 OAuth 페이지로 리다이렉션
- 로그인 완료시 원래의 페이지로 리다이렉션

### 인수 시나리오
- 라이브러리를 빌드해서 로컬에서 테스트 완료

**Comment by juy4556** [comment]
🔥
